Repository depromeet/oversweet-core, pull requests merged in 2023-06, with the labels that each got.

#2 [Feat] 프로젝트 초기 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  oversweet-api/build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/OversweetApiApplication.java
  oversweet-api/src/main/java/com/depromeet/oversweet/TestController.java
  oversweet-api/src/main/resources/application.yml
  oversweet-api/src/test/java/com/depromeet/oversweet/OversweetApiApplicationTests.java
  oversweet-common/build.gradle
  oversweet-common/src/main/java/com/depromeet/oversweet/TestException.java
  oversweet-common/src/test/java/com/depromeet/oversweet/OversweetCommonApplicationTest.java
  oversweet-domain/build.gradle
  oversweet-domain/src/main/java/com/depromeet/oversweet/TestDomain.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/OversweetDomainApplicationTests.java
  oversweet-infra/build.gradle
  oversweet-infra/src/main/java/com/depromeet/oversweet/TestInfra.java
  oversweet-infra/src/main/resources/application.yml
  oversweet-infra/src/test/java/com/depromeet/oversweet/OversweetInfraApplicationTests.java
  settings.gradle
Labels: ⚙ Setting, 💎수찬💎

#5 [Feature] core 서버에서 사용하는 엔티티를 설계했어요.
  README.md
  oversweet-api/src/main/resources/application-local.yml
  oversweet-api/src/main/resources/application.yml
  oversweet-domain/build.gradle
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/DrinkBookmarkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/FranchiseBookmarkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/common/entity/BaseTimeEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/config/JpaEntityConfig.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/entity/DrinkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/enums/DrinkCategory.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/entity/FranchiseEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/entity/MemberEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/enums/Gender.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/enums/SocialProvider.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
Labels: ✨ Feature, 🌷정현🌷

#7 [Feature] : ecs, ecr 배포 환경 구축
  .aws/task-definition.json
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/TestController.java
  oversweet-api/src/main/resources/application-local.yml
  oversweet-api/src/main/resources/application-prod.yml
  oversweet-api/src/main/resources/application.yml
  oversweet-api/src/test/resources/application-test.yml
  oversweet-api/src/test/resources/application.yml
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseEntityRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/service/FranchisePureService.java
Labels: ✨ Feature, 💎수찬💎

#9 [Refactor] : develop에 push 된 경우에만 배포 하도록 수정
  .github/workflows/deploy.yml
Labels: ⚙ Setting, 💎수찬💎

#11 [Feature] : QueryDSL & Swagger & Cors 설정 추가
  oversweet-api/build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/TestController.java
  oversweet-api/src/main/resources/application-local.yml
  oversweet-common/build.gradle
  oversweet-common/src/main/java/com/depromeet/oversweet/config/WebMvcConfig.java
  oversweet-common/src/main/java/com/depromeet/oversweet/swagger/OpenApiConfig.java
  oversweet-domain/build.gradle
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseEntityFilter.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseEntityFilterImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseEntityRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/service/FranchisePureService.java
Labels: ✨ Feature, 💎수찬💎

#13 📦 [Chore] 이슈 및 PR 탬플릿 수정
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 💎수찬💎, 📦Chore

#16 ✨ [Feat] exception 핸들링 기능 추가
  oversweet-api/src/main/java/com/depromeet/oversweet/TestController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/TestDataRequestDto.java
  oversweet-api/src/main/java/com/depromeet/oversweet/TestDataResponseDto.java
  oversweet-common/src/main/java/com/depromeet/oversweet/TestException.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorResponse.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/GlobalExceptionHandler.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/OverSweetException.java
  oversweet-common/src/main/java/com/depromeet/oversweet/response/DataResponse.java
  oversweet-common/src/main/java/com/depromeet/oversweet/response/DefaultResponse.java
  oversweet-common/src/main/java/com/depromeet/oversweet/response/MessageResponse.java
Labels: ✨ Feature, 💎수찬💎

#19 ✨ [Feat] 유저가 즐겨찾기한 프랜차이즈 목록 조회 기능 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/FranchiseBookMarkedInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/FranchiseBookMarkedResponseDto.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/FranchiseBookMarkSearchService.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/OversweetDomainApplication.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/FranchiseBookmarkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/common/entity/BaseTimeEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/entity/FranchiseEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/service/FranchisePureService.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/entity/MemberEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/member/repository/MemberJpaRepository.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepositoryTest.java
Labels: ✨ Feature, 💎수찬💎

#21 🐛 [Fix] Test Task가 실패하여, Build 되지 않던 문제를 해결
  oversweet-domain/src/main/java/com/depromeet/oversweet/OversweetDomainApplication.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/OversweetDomainApplicationTests.java
Labels: 🛠 Fix, 💎수찬💎
