Repository depromeet/oversweet-core, pull requests merged in 2023-07, with the labels that each got.

#23 ✨ [Feat] 유저가 즐겨 찾기한 음료 목록 조회 기능 구현
  build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/DrinkBookMarkedInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/DrinkBookMarkedResponseDto.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/FranchiseBookMarkedInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/FranchiseBookMarkedResponseDto.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/FranchiseInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/DrinkBookMarkSearchService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/FranchiseBookMarkSearchService.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/DrinkBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindDrinkBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindDrinkBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/DrinkJpaRepository.java
Labels: ✨ Feature, 💎수찬💎

#27 ✨ [Feat] 유저가 특정 프랜차이즈 즐겨찾기 기능 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/FranchiseBookMarkRegisterService.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/bookmark/AlreadyFranchiseBookMarked.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/franchise/NotFoundFranchiseException.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/FranchiseBookmarkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/RegisterFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/RegisterFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseJpaRepository.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/TestConfig.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepositoryTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/record/repository/TestConfig.java
  oversweet-domain/src/test/resources/application.yml
Labels: ✨ Feature, 💎수찬💎

#30 🐛 [Fix] Jpa Naming Method 규칙에 맞게 메서드 네이밍 수정
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepository.java
Labels: 🛠 Fix, 💎수찬💎

#32 ✨ [Feat] 유저가 특정 음료을 즐겨찾기 하는 기능 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/DrinkBookMarkRegisterService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/FranchiseBookMarkRegisterService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/DrinkDailySugarTotalStatisticsInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/LocalDateTimeInfo.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/vo/DrinkStatisticsTotalInfoTest.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/vo/LocalDateTimeInfoTest.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/drink/AlreadyDrinkBookMarked.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/drink/NotFoundDrinkException.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/entity/DrinkBookmarkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/DrinkBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindDrinkBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindDrinkBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/RegisterDrinkBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/RegisterDrinkBookMarkRepositoryImpl.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/bookmark/repository/FindDrinkBookMarkRepositoryImplTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImplTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepositoryImplTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseRepositoryImplTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/member/repository/FindMemberRepositoryImplTest.java
Labels: ✨ Feature, ✅ Test, 💎수찬💎

#36 ✨ [Feat] 유저의 주간 당 통계 정보를 조회 하는 API를 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/common/dto/response/FranchiseInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/common/dto/response/MemberInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/request/DrinkWeeklySugarDateRequest.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkDailyDetailInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkDailySugarInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkDailySugarStatisticsResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkDailySugarTotalStatisticsInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkWeeklySugarStatisticsResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkWeeklySugarTotalStatisticsInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkDailyStatisticsService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkWeeklyStatisticsService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/DrinkStatisticsTotalInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/LocalDateTimeInfo.java
  oversweet-api/src/test/java/com/depromeet/oversweet/common/TestSetup.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/service/DrinkDailyStatisticsServiceTest.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/service/DrinkWeeklyStatisticsServiceTest.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/vo/DrinkStatisticsTotalInfoTest.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryImpl.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryTest.java
Labels: ✨ Feature, ⭐제준⭐

#38 ⚙️ [Ci] PR 올리면 Test 수행하도록 script 추가
  .github/workflows/pr-test.yml
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/member/entity/MemberEntityTest.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/record/entity/RecordEntityTest.java
Labels: ⚙ Setting, 💎수찬💎

#40 ✨ [Feat] 프랜차이즈 즐겨찾기 해제 기능 구현
  build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/dto/response/FranchiseBookMarkedInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/FranchiseBookMarkRegisterService.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/vo/LocalDateTimeInfoTest.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/UpdateFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/UpdateFranchiseBookMarkRepositoryImpl.java
Labels: ✨ Feature, 💎수찬💎

#44 📦 [Chore] 임시적으로 API 접근자 유저 ID를 100으로 통일
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
Labels: 💎수찬💎, 📦Chore

#46 ✨ [Feat] Swagger 설정에 Server 도메인 주소 추가
  oversweet-common/src/main/java/com/depromeet/oversweet/swagger/OpenApiConfig.java
Labels: ✨ Feature, 💎수찬💎

#48 ✨ [Feat] 유저가 즐겨 찾기한 음료 해제 기능을 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/service/DrinkBookMarkRegisterService.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/DrinkBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/UpdateDrinkBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/UpdateDrinkBookMarkRepositoryImpl.java
Labels: ✨ Feature, 💎수찬💎

#49 ✨ [Feature] 프랜차이즈 검색 API를 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/common/dto/response/FranchiseInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/controller/FranchiseController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/service/FranchiseSearchService.java
  oversweet-api/src/test/java/com/depromeet/oversweet/franchise/FranchiseSearchServiceTest.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseSearchRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseSearchRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FranchiseJpaRepository.java
Labels: ✨ Feature, ⭐제준⭐

#50 ✨ [Feature] 마신 음료에 대한 당 기록 기능을 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/record/controller/RecordController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/dto/request/DrinkRecordSaveRequest.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/dto/response/DrinkRecordSaveResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/service/DrinkRecordSaveService.java
  oversweet-api/src/test/java/com/depromeet/oversweet/common/TestSetup.java
  oversweet-api/src/test/java/com/depromeet/oversweet/record/service/DrinkRecordSaveServiceTest.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/entity/RecordEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/SaveRecordRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/SaveRecordRepositoryImpl.java
Labels: ✨ Feature, 🌷정현🌷

#52 ✨ [Feature] 프랜차이즈 정보 레디스에서 가져오는 API를 구현했어요
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/controller/FranchiseController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/service/FranchiseRedisService.java
  oversweet-api/src/main/resources/application-local.yml
  oversweet-api/src/main/resources/application-prod.yml
  oversweet-api/src/test/resources/application-test.yml
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/redis/OverSweetRedisException.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindAllFranchiseRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindAllFranchiseRepositoryImpl.java
  oversweet-infra/build.gradle
  oversweet-infra/src/main/java/com/depromeet/oversweet/redis/RedisConfig.java
  oversweet-infra/src/main/java/com/depromeet/oversweet/redis/RedisRepository.java
  redis-server.yml
Labels: ✨ Feature, ⭐제준⭐

#54 ✨ [Feature] 음료 상세보기 기능을 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/request/DrinkInfoRequest.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkDetailInfoResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkDetailSearchService.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/dto/DrinkInfoWithScrapStatus.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/entity/DrinkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/DrinkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepositoryImpl.java
Labels: ✨ Feature, 💎수찬💎

#56 ✨ [Feature] Security 설정과 Authentication 검증 어노테이션 추가를 구현했어요.
  oversweet-api/build.gradle
  oversweet-api/src/main/java/com/depromeet/oversweet/TestController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/member/controller/MemberController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/controller/RecordController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/config/SecurityConfig.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/filter/ExceptionFilter.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/filter/JwtAuthenticationFilter.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/handler/JwtAuthenticationEntryPointHandler.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/jwt/JwtTokenProvider.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/jwt/TokenResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/service/CustomUserDetails.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/service/CustomUserDetailsService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/util/JwtTokenProvider.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/security/ExpiredTokenException.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/security/InvalidTokenException.java
  oversweet-common/src/main/java/com/depromeet/oversweet/swagger/OpenApiConfig.java
Labels: ⚙ Setting, ✨ Feature, 🌷정현🌷

#58 ✨ [Feature] 음료의 간편 정보를 Redis에서 가져오는 API 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkRedisInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkRedisService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/controller/FranchiseController.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/dto/DrinkSimpleInfo.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/enums/DrinkCategory.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/DrinkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindAllDrinkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindAllDrinkRepositoryImpl.java
Labels: ✨ Feature, ⭐제준⭐

#60 ✨ [Feature] 프랜차이즈 기준, 가장 인기가 많은 음료 조회
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/LocalDateTimeInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/controller/FranchiseController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/dto/response/FranchiseInfoWithScrapStatus.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/dto/response/MostPopularDrinkResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/service/FranchiseSearchService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/config/SecurityConfig.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FindFranchiseBookMarkRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/bookmark/repository/FranchiseBookMarkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseSearchRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/franchise/repository/FindFranchiseSearchRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/dto/RankingDrink.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/RecordJpaRepository.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/TestConfig.java
Labels: ✨ Feature, 💎수찬💎

#63 ✨ [Feature] 프랜차이즈 페이지 내 음료 키워드로 검색 API를 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkAllInfoResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkSearchService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/DrinkSameNameInfo.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinksByFranchiseAndKeywordRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinksByFranchiseAndKeywordRepositoryImpl.java
Labels: ✨ Feature, ⭐제준⭐

#65 🚑 [Hotfix] core 서버에서의 Swagger Security 오류를 해결했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/bookmark/controller/BookmarkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/franchise/controller/FranchiseController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/member/controller/MemberController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/controller/RecordController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/config/SecurityConfig.java
  oversweet-common/src/main/java/com/depromeet/oversweet/annotation/SecurityExclusion.java
  oversweet-common/src/main/java/com/depromeet/oversweet/swagger/OpenApiConfig.java
Labels: 🐞Bug, 🌷정현🌷

#70 ✨ [Feat] 당 성분이 비슷한 음료 추천 기능 구현
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkRecommendInfo.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/dto/response/DrinkRecommendResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/service/DrinkRecommendService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/vo/SugarDiffState.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/config/SecurityConfig.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/entity/DrinkEntity.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/DrinkJpaRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinkRepositoryImpl.java
Labels: ✨ Feature, 💎수찬💎

#68 ✨ [Feat] 프랜차이즈, 음료 카테고리, 정렬 조건에 따라 음료 목록을 조회하는 기능을 구현했어요.
  oversweet-api/src/main/java/com/depromeet/oversweet/drink/controller/DrinkController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/search/controller/SearchController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/search/dto/response/DrinkAllInfoResponse.java
  oversweet-api/src/main/java/com/depromeet/oversweet/search/service/DrinkSearchService.java
  oversweet-api/src/main/java/com/depromeet/oversweet/security/config/SecurityConfig.java
  oversweet-api/src/test/java/com/depromeet/oversweet/common/TestSetup.java
  oversweet-api/src/test/java/com/depromeet/oversweet/drink/service/DrinkSearchServiceTest.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinksByFranchiseAndCategoryRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinksByFranchiseAndCategoryRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/drink/repository/FindDrinksSearchRepositoryImpl.java
  oversweet-domain/src/test/java/com/depromeet/oversweet/domain/TestConfig.java
Labels: ✨ Feature, 🌷정현🌷

#72 ✨ [Feat] 음료 기록 삭제 API를 구현했어요. (#71)
  oversweet-api/src/main/java/com/depromeet/oversweet/record/controller/RecordController.java
  oversweet-api/src/main/java/com/depromeet/oversweet/record/service/DrinkRecordSaveService.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/ErrorCode.java
  oversweet-common/src/main/java/com/depromeet/oversweet/exception/record/NotFoundRecordException.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/DeleteRecordRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/DeleteRecordRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepository.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/FindRecordsRepositoryImpl.java
  oversweet-domain/src/main/java/com/depromeet/oversweet/domain/record/repository/RecordJpaRepository.java
Labels: ✨ Feature, ⭐제준⭐
